"""Constants for QR workflow (event types, versions, error codes)."""

FINALIZATION_RULE_VERSION = 1

EVENT_CARD_ASSIGNED = "CARD_ASSIGNED"
EVENT_BAG_CLAIMED = "BAG_CLAIMED"
EVENT_BLISTER_COMPLETE = "BLISTER_COMPLETE"
EVENT_SEALING_COMPLETE = "SEALING_COMPLETE"
EVENT_PACKAGING_SNAPSHOT = "PACKAGING_SNAPSHOT"
EVENT_BAG_FINALIZED = "BAG_FINALIZED"
EVENT_CARD_FORCE_RELEASED = "CARD_FORCE_RELEASED"
EVENT_STATION_SCAN_TOKEN_ROTATED = "STATION_SCAN_TOKEN_ROTATED"

QR_CARD_STATUS_IDLE = "idle"
QR_CARD_STATUS_ASSIGNED = "assigned"
