#!/bin/bash
# Deployment Script for TabletTracker v1.37.1
# Major UI optimizations: Compact tables, redesigned Overview section

echo "=================================================="
echo "TabletTracker v1.37.1 Production Deployment"
echo "=================================================="
echo ""

# Set variables
PYTHONANYWHERE_USER="sahilk1"
APP_PATH="/home/$PYTHONANYWHERE_USER/TabletTracker"

echo "📋 Deployment Checklist:"
echo "✓ All changes committed to GitHub"
echo "✓ Database migration included (auto-runs in init_db)"
echo "✓ UI optimizations for dashboard tables"
echo ""

echo "🔄 Step 1: Pull latest code from GitHub"
echo "ssh $PYTHONANYWHERE_USER@ssh.pythonanywhere.com"
echo "cd $APP_PATH"
echo "git pull origin main"
echo ""

echo "📊 Step 2: Backup database (RECOMMENDED)"
echo "cp tablet_counter.db tablet_counter.db.backup_$(date +%Y%m%d_%H%M%S)"
echo ""

echo "🔧 Step 3: Database Migration"
echo "The following migration will run automatically on app start:"
echo "  - Add 'po_assignment_verified' column (if not exists)"
echo "  - All existing submissions default to unverified (need manager approval)"
echo ""

echo "🔄 Step 4: Reload web app"
echo "Go to: https://www.pythonanywhere.com/user/$PYTHONANYWHERE_USER/webapps/#tab_id_$PYTHONANYWHERE_USER.pythonanywhere.com"
echo "Click the 'Reload' button"
echo ""

echo "✅ Step 5: Verify deployment"
echo "Visit: https://$PYTHONANYWHERE_USER.pythonanywhere.com/dashboard"
echo "Check:"
echo "  ✓ Overview section is wide and compact (3 columns)"
echo "  ✓ Production Reports section is narrow and centered"
echo "  ✓ Active POs table has no horizontal scroll"
echo "  ✓ Recent Submissions table has no horizontal scroll"
echo "  ✓ All existing submissions show 'Approve' or 'Change' buttons"
echo ""

echo "=================================================="
echo "QUICK DEPLOY COMMANDS (copy/paste to terminal):"
echo "=================================================="
echo ""
echo "ssh $PYTHONANYWHERE_USER@ssh.pythonanywhere.com << 'ENDSSH'"
echo "cd $APP_PATH"
echo "cp tablet_counter.db tablet_counter.db.backup_\$(date +%Y%m%d_%H%M%S)"
echo "git pull origin main"
echo "echo '✅ Code updated successfully'"
echo "echo '⚠️  Now reload your web app at PythonAnywhere dashboard'"
echo "ENDSSH"
echo ""

echo "=================================================="
echo "📝 CHANGELOG v1.37.1:"
echo "=================================================="
echo ""
echo "🎨 UI OPTIMIZATIONS:"
echo "  ✅ Overview section: Redesigned to wide 3-column layout (50% shorter)"
echo "  ✅ Production Reports: Narrower, centered section"
echo "  ✅ Data Management: Moved to bottom, 3-column compact layout"
echo "  ✅ Active POs table: No horizontal scroll, compact columns"
echo "  ✅ Recent Submissions table: No horizontal scroll, compact columns"
echo "  ✅ Removed 'Show Closed POs' checkbox from Recent Submissions"
echo ""
echo "🔧 TECHNICAL CHANGES:"
echo "  ✅ Table padding reduced: px-6 py-4 → px-2 py-2"
echo "  ✅ Font sizes reduced: text-sm → text-xs"
echo "  ✅ Status badges: Icon-only for compact display"
echo "  ✅ Column headers: Abbreviated for space saving"
echo "  ✅ Progress bars: Narrower and thinner"
echo "  ✅ Numeric columns: Center-aligned"
echo ""
echo "📊 SOFT ASSIGNMENT WORKFLOW:"
echo "  ✅ All submissions need PO verification"
echo "  ✅ Managers can approve or change assignments"
echo "  ✅ Once approved/changed, assignment is locked"
echo ""

echo "=================================================="
echo "🚨 IMPORTANT NOTES:"
echo "=================================================="
echo ""
echo "1. DATABASE MIGRATION:"
echo "   - Runs automatically on app start"
echo "   - Adds 'po_assignment_verified' column"
echo "   - Existing submissions default to FALSE (need verification)"
echo "   - Safe to run multiple times (checks for existing column)"
echo ""
echo "2. EXISTING DATA:"
echo "   - All existing PO assignments preserved"
echo "   - Managers need to verify/approve assignments"
echo "   - Verification count will show all unverified submissions"
echo ""
echo "3. USER IMPACT:"
echo "   - Dashboard loads faster (less HTML)"
echo "   - No horizontal scrolling needed"
echo "   - All info visible at once"
echo "   - Cleaner, more modern UI"
echo ""
echo "4. ROLLBACK (if needed):"
echo "   - Restore backup: cp tablet_counter.db.backup_TIMESTAMP tablet_counter.db"
echo "   - Git revert: git checkout v1.35.8 (or previous version)"
echo "   - Reload web app"
echo ""

echo "=================================================="
echo "🎯 POST-DEPLOYMENT VERIFICATION:"
echo "=================================================="
echo ""
echo "1. Login as admin (admin/admin)"
echo "2. Check Overview section:"
echo "   ✓ 3 columns: PO Stats, PO Verification, Zoho Setup"
echo "   ✓ Takes less vertical space"
echo "3. Check Active Purchase Orders:"
echo "   ✓ No horizontal scroll bar"
echo "   ✓ All columns visible"
echo "   ✓ Status shows as icons"
echo "4. Check Recent Submissions:"
echo "   ✓ No horizontal scroll bar"
echo "   ✓ All columns visible"
echo "   ✓ Submissions show Approve/Change buttons"
echo "5. Test functionality:"
echo "   ✓ Click PO row to view details (modal)"
echo "   ✓ Approve a submission"
echo "   ✓ Change PO assignment"
echo "   ✓ Generate a report"
echo ""

echo "=================================================="
echo "✅ Ready to deploy!"
echo "=================================================="
echo ""
echo "Current version: v1.37.1"
echo "Previous version: v1.15.8"
echo ""
echo "Estimated deployment time: 2-3 minutes"
echo "Downtime: ~10 seconds (web app reload)"
echo ""

